<?php
# This file was automatically generated by the MediaWiki 1.35.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = 'The Repository';
$wgMetaNamespace = "The_Repository";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = ".php";
$wgArticlePath = "/$1";
$wgUsePathInfo = true;

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://www.therepository.net";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = 'accounts@arteeh.com';
$wgPasswordSender = 'accounts@arteeh.com';

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "u61973p83116_mw1";
$wgDBuser = "u61973p83116_mw1";
$wgDBpassword = "Q#8rJd3jRYoyer^Src^33,)5";

# MySQL specific settings
$wgDBprefix = "mw_";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

## Shared memory settings
$wgMainCacheType = CACHE_MEMCACHED;
$wgMemCachedServers = [ '10.0.24.1:10480' ];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgGenerateThumbnailOnParse = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = 'en';

$wgSecretKey = "d9baefb5840c0e92c041ceb267ea3ca5a7af1b08309487621bec1229957e07bd";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "9d24ec8af6714095";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# --- BELOW IS CUSTOM ---

# Better editor
wfLoadExtension( 'WikiEditor' );

# Cookie warning as per GDPR laws
wfLoadExtension( 'CookieWarning' );
$wgCookieWarningEnabled = true;

# Embed videos. This will probably come in handy later.
wfLoadExtension( 'EmbedVideo' );

# Allow adding scripts to <head> for ThatsWhy SEO things
wfLoadExtension( 'HeadScript' );
$wgHeadScriptCode = <<<'START_END_MARKER'
<script async defer src="https://collector.thatswhy.app/y92m4bKgZp.js"></script>
START_END_MARKER;

# Required for CSS from the Star Citizen wiki
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TemplateStyles' );
wfLoadExtension( 'TextExtracts' );

# Popup when hovering over a page link, just like Wikipedia
wfLoadExtension( 'TextExtracts' ); # dependency
wfLoadExtension( 'PageImages' ); # dependency
wfLoadExtension( 'Popups' );
$wgPopupsHideOptInOnPreferencesPage = true;
$wgPopupsOptInDefaultState = '1';
$wgPopupsReferencePreviewsBetaFeature = false;

# Citizen skin
wfLoadSkin( 'Citizen' );
$wgDefaultSkin = "citizen";

# Favicon
$wgFavicon = "/favicons/favicon.ico";

# Sword logo
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/grsword.png" ];

# Citizen customization; https://github.com/StarCitizenTools/mediawiki-skins-Citizen
$wgCitizenEnableLazyload = true;
$wgCitizenEnableDenyXFrameOptions = true;
$wgCitizenEnableXXSSProtection = true;
$wgCitizenEnableManifest = true;
$wgCitizenManifestThemeColor = 0xc9134d;
$wgCitizenManifestBackgroundColor = 0x000;
$wgCitizenThemeColor = 0x222226;
$wgCitizenShowPageTools = login;

# Permissions
$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['user']['createpage'] = true;
